### ISSUE TITLE
feat: file should be an instance of Blob

### ISSUE THREAD

**Issue by 3zzy** [capawesome-team/capacitor-file-picker#25]
On the web, the picker returns an object and optionally base64 string if `readData` is enabled. 

I could convert base64 to Blob but ideally it should just return a Blob like the native file picker which is easier to work with without any conversions required.

Thanks

**Comment by reslear** [comment]
hi @robingenz pr about this is welcome?

**Comment by robingenz** [comment]
> hi @robingenz pr about this is welcome?

Yes, I propose the following extension:

```diff
export interface File {
...
+ /**
+    * The Blob instance of the file.
+    * 
+    * Only available on Web.
+    */
+ blob?: Blob;
}
```

**Comment by reslear** [comment]
> > hi @robingenz pr about this is welcome?
> 
> Yes, I propose the following extension:
> 
> ```diff
> export interface File {
> ...
> + /**
> +    * The Blob instance of the file.
> +    * 
> +    * Only available on Web.
> +    */
> + blob?: Blob;
> }
> ```

good, and in the final we get backward compatibility with [File](https://developer.mozilla.org/en-US/docs/Web/API/File/File) :

```ts
const rawFile = new File(file.blob, file.name, {
  type: file.mimeType,
});

formData.append('file', rawFile, file.name);
```

**Comment by reslear** [comment]
@robingenz or return raw file: 
```diff
export interface FilePickerResponse {
...
+ /**
+    * The File instance
+    * 
+    * Only available on Web.
+    * docs: https://developer.mozilla.org/en-US/docs/Web/API/File
+    */
+ raw?: File;
}
```
