### ISSUE TITLE
feat: Specify image/* or audio/* or video/* mimeTypes

### ISSUE THREAD

**Issue by Sharcoux** [capawesome-team/capacitor-file-picker#28]
**Is your feature request related to a problem? Please describe:**

We want to pick any image like files and it would be easier to just use `image/*`

**Describe the solution you'd like:**

Make the picker accept `image/*` and the likes

**Describe alternatives you've considered:**

Provide a constant resolving to the actual list of mime types that would match `image/*`

**Additional context:**

**Comment by robingenz** [comment]
Have you tried whether that might not already work?

**Comment by Sharcoux** [comment]
Hum... I trusted the dev that handled it, but I might give it a check myself :sweat_smile: 

Might be good to mention this in the ReadMe though.

**Comment by robingenz** [comment]
No, please don't get me wrong. I don't know if it works. I pass the MimeTypes to the OS and I don't know how they handle them. That's why the question.

**Comment by Sharcoux** [comment]
Ok, let me double check then.

**Comment by zawmn** [comment]
When I tried, video/* is only working in Android.  In iOS, it is not working.  
I tried to Save to Files the video from iPhone galley to iPhone folder. 
The video file show in list but it is dimmed and can't choose in picker. 
Is it normal behavior ?
Could you guide me which video mime type need to set to pick up the video that I take with iPhone camera?  
In gallery it show HEVC in video info.  I'm not sure which MIME type need to set in code to support this.

**Comment by robingenz** [comment]
> The video file show in list but it is dimmed and can't choose in picker.
> Is it normal behavior ?

Yes, it means that the selected mime type does not match the file.

> Could you guide me which video mime type need to set to pick up the video that I take with iPhone camera?

Should be `video/mp4`.

Please only comment on this issue that are really related. Otherwise please create a new issue.
