### ISSUE TITLE
How this plugin is Different from input type="file"

### ISSUE THREAD

**Issue by Saqib92** [capawesome-team/capacitor-file-picker#33]
Q: How this plugin is different from `<input type="file"/>`. what are the advantages? as i have seen some issues related to large files and etc. input type file offers same functionality.

**Plugin version:**

All

**Platform(s):**
Android
IOS

**Current behavior:**

Pick file from Device.

**Comment by robingenz** [comment]
I haven't tested it in detail but of course with `<input type="file"/>` you don't have access to [`path: string`](https://github.com/capawesome-team/capacitor-file-picker#file).
In combination with another plugin, you could natively upload large files that the user selects, etc.
Just try `<input type="file"/>` and if you don't miss anything then stick with it.
