### ISSUE TITLE
Android: Can't select file. Files are disabled

### ISSUE THREAD

**Issue by sajjadalis** [capawesome-team/capacitor-file-picker#35]
As mentioned in the title, the Select box, can't choose any files. It won't even click on them and they're disabled with gray color. Please check the screenshots.

![](https://i.imgur.com/yWesJGv.jpg)
![](https://i.imgur.com/zQ2PttW.jpg)

This is probably not the plugin issue as I have tried `<input type="file" />` but same results. Works fine on Windows in both cases.
```
const pickFile = async () => {
	const result = await FilePicker.pickFiles({
		types: ["text/csv"],
	});
	if (result) {
		content.value = result.files[0];
		console.log(content.value);
	}
}
```
Also please note that while on windows, it shows CSV files as set in types but on Android, it's showing all types of files. Not sure if that is how file selection works on Android.

I have tested this on Xiaomi 11T with MIUI v13.0.3, Android version 12, and OnePlus 5T with PixelExperience, Andoird version 12.

Any suggestion, what am I doing wrong? Is it some kind of android security?

Thanks

**Comment by robingenz** [comment]
Hi @sajjadalis,
thank you for your request.

> Also please note that while on windows, it shows CSV files as set in types but on Android, it's showing all types of files. Not sure if that is how file selection works on Android.

This is how file selection works on Android.

> Any suggestion, what am I doing wrong?

Have you tried `application/vnd.ms-excel` or `application/excel` instead of `text/csv` as type?

**Comment by sajjadalis** [comment]
Thank you. `text/comma-separated-values` working. 

Appreciate the help.

**Comment by robingenz** [comment]
I will add a mime type mapping to handle this.
