### ISSUE TITLE
bug:   "FilePicker.pickFiles()" is not implemented on android

### ISSUE THREAD

**Issue by pitamash** [capawesome-team/capacitor-file-picker#44]
**Plugin version:**

Plugin version v0.4.0 

**Platform(s):**

Ionic 6 Capcitor 4;
 

**Current behavior:**

I get when after selecting the file;

core.mjs:7640 ERROR Error: Uncaught (in promise): Error: "FilePicker.pickFiles()" is not implemented on android
Error: "FilePicker.pickFiles()" is not implemented on android

I havent tried on ios yet;
Kindly  help.

**Expected behavior:**

 return  selected files; 

**Steps to reproduce:**

**Related code:**

```
npm install @capawesome/capacitor-file-picker
npx cap sync

import { FilePicker } from '@capawesome/capacitor-file-picker';

 getFile(){
          const fileResult = await FilePicker.pickFiles({ 
              multiple: false
          }) ; 
          console.log(webfile);
    }
```

**Other information:**

Testing on Android Studio
Android Studio Arctic Fox | 2020.3.1 Patch 3
Build #AI-203.7717.56.2031.7784292, built on October 1, 2021
Runtime version: 11.0.10+0-b96-7249189 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/ios: not installed
  @capacitor/cli: 4.0.1
  @capacitor/core: 4.0.0
  @capacitor/android: 4.0.1

```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by pitamash** [comment]
Thanks. I ended up using up using fileReader to achieve this, i know it's not the most accurate way but at least it got this working on android for picking files using <input type="file">;

at the top of the page;  i added
`
export function getFileReader(): FileReader {
  const fileReader = new FileReader();
  const zoneOriginalInstance = (fileReader as any)["__zone_symbol__originalInstance"];
  return zoneOriginalInstance || fileReader;
}`

Then in my function 

`
fileOnchange(ev){
const fileReader =   getFileReader()
            inputfile = ev.target.files[0]; ; 
             fileReader.onloadend = (e) => { 
                       return( fileReader.result );
             },
            fileReader.onerror = (e)=>{
                      console.log(e) ;
                      return(e)
           } ;
          fileReader.readAsArrayBuffer(inputfile);  
}
`

**Comment by robingenz** [comment]
I will close this issue as I do not have a minimal, reproducible example to debug.
