### ISSUE TITLE
bug: pdf base64 encoding problem on Android

### ISSUE THREAD

**Issue by OneGoodReas0n** [capawesome-team/capacitor-file-picker#45]
**Plugin version:**

0.3.0

**Platform(s):**

android 11

**Current behavior:**

After I am choosing a PDF file and trying to get base64encoding `file.data`, this data is not equal to the result of base64 encoding from encoder https://base64.guru/converter/encode/file

**Expected behavior:**

I expect the result of `file.data` to be equal to base64 encoding value.

**Steps to reproduce:**

* Pick a PDF file
* Read the `file.data`
* Compare it with base64 encoder result (for instance https://base64.guru/converter/encode/file)

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
I will look into this.

**Comment by OneGoodReas0n** [comment]
@robingenz the problem is that after we are getting the base64 of the file, there are line breaks in the result string. After removing line breaks with `replace(/\r?\n|\r/g, '')` everything works perfectly.

**Comment by robingenz** [comment]
@OneGoodReas0n Thank you for reporting and debugging!
