### ISSUE TITLE
feat: Open file with custom file extension on iOS

### ISSUE THREAD

**Issue by GabrielNSD** [capawesome-team/capacitor-file-picker#47]
**Is your feature request related to a problem? Please describe:**

I have a custom file type in my project (.cs2). It is, basically, a file with a `application/zip` mime type and a `cs2` file extension.  
Passing its mime type to file picker still does not make the file pickable on iOS.

**Describe the solution you'd like:**

It would be great to also define the allowed file extensions when calling `pickFiles` method.

**Describe alternatives you've considered:**

I have considered using another init method for `UiDocumentPickerViewController`, the `init(forOpeningContentTypes: [UTType])`. [reference](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller/3566732-init).  
Using this method, with a type initialized with `UTType(filenameExtension)`. [reference](https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/3551510-init).  
Using this methods in a bare swift application woks, tested on iOS16.

**Additional context:**

**Comment by robingenz** [comment]
@GabrielNSD Thank you for your request.

Does it work on Android and Web or did you only test it on iOS?

And please provide a file with custom file type for testing.
