### ISSUE TITLE
bug: Files of type "text/csv" are not selectable on Android when "text/csv" is specified within `types`

### ISSUE THREAD

**Issue by jonesdhtx** [capawesome-team/capacitor-file-picker#50]
**Plugin version:**
0.5.0

**Platform(s):**
Android

**Current behavior:**
Specifying the type `"text/csv"` does not allow files of type `"text/csv"` to be selectable in the ui (they are grayed out) because `FilePickerPlugin.java@parseTypesOption` method is replacing `"text/csv"` with `"text/comma-separated-values"`. 
[See: FilePickerPlugin.java](https://github.com/capawesome-team/capacitor-file-picker/blob/main/android/src/main/java/io/capawesome/capacitorjs/plugins/filepicker/FilePickerPlugin.java#L62)

**Expected behavior:**
We're expecting that specifying the type of `"text/csv"` will allow files of type `"text/csv"` to be selected.

We wish to specify the following types:
```
['text/csv', 'text/comma-separated-values', 'application/csv']
```
but after replacement it is yielding a picker filtering these values:
```
['text/comma-separated-values', 'text/comma-separated-values', 'application/csv']
```

**Steps to reproduce:**
* have a file with type of "text/csv" on your device
* invoke picker and note that the file is grayed out and not selectable
```
await FilePicker.pickFiles({ 
  types: ['text/csv', 'text/comma-separated-values', 'application/csv'],
  multiple: false 
})
```

**Related code:**
Following line of code prevents selection of any file with mime-type of `"text/csv"`
[See: FilePickerPlugin.java](https://github.com/capawesome-team/capacitor-file-picker/blob/main/android/src/main/java/io/capawesome/capacitorjs/plugins/filepicker/FilePickerPlugin.java#L62)

**Other information:**
We need to be able to specify all three types for selection:
```
 ['text/csv', 'text/comma-separated-values', 'application/csv']
```

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

Installed Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/ios: 4.3.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
The mapping was added so you don't have to select different mime types depending on the platform. `text/csv` did not work on Android according to #35.

**Comment by jonesdhtx** [comment]
> The mapping was added so you don't have to select different mime types depending on the platform. `text/csv` did not work on Android according to #35.

Right. The mapping idea is neat but it causes another issue in that some csv files do not match on "text/comma-separated-values" alone (ie they become selectable only when types are extended to also include "text/csv").  

I have a csv file that is dimmed out (unavailable for selection) when the types are defined as only 
```
intent.putExtra(Intent.EXTRA_MIME_TYPES, ["text/comma-separated-values", "application/csv"]);
```
but it *is* selectable (not dimmed out) if the types are defined as 
```
intent.putExtra(Intent.EXTRA_MIME_TYPES, ["text/csv", "text/comma-separated-values", "application/csv"]);
```

Trying to put another way: the mapping prevents some csv files from being selected. To me, the best approach for any automatic mapping would be to map:
```
["text/csv"] ==> to ==> ["text/csv", "text/comma-separated-values", "application/csv"]
```
to cast the widest net possible to catch all potential csv files.

**Comment by robingenz** [comment]
Great idea, I had thought about that as well.
Feel free to test this dev build:
```
npm i @capawesome/capacitor-file-picker@0.5.1-dev.1d0b6df.1665431290
```

But I have omitted `application/csv` for now. Otherwise we would need the same mapping for iOS and Web since I assume that it works there as desired.
