### ISSUE TITLE
bug: Blob is not generated for android , Works fine for web

### ISSUE THREAD

**Issue by abhilashsajeev** [capawesome-team/capacitor-file-picker#52]
**Plugin version:**

0.5.2

**Platform(s):**

Android

**Current behavior:**

Creates Blob only in web file picker but same is not seen in android web view. But data like path, name, etc are present

**Expected behavior:**

Should show picked file blob in android also

**Steps to reproduce:**

the file picker example in the example repo, try in it android web view. No blob present in the result.

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/android: 4.3.0
  @capacitor/core: 4.3.0
  @capacitor/ios: 4.3.0
  @capacitor/android: 4.3.0

[success] Android looking great! 
```

**Comment by robingenz** [comment]
Thank you for your request.
Have a look at the documentation: 
> The Blob instance of the file. Only available on Web.

This is not a bug. It’s just not supported on Android and iOS.

**Comment by abhilashsajeev** [comment]
Nevermind. Not available on web
