### ISSUE TITLE
What happens if multiple = true on Android?

### ISSUE THREAD

**Issue by de-dan** [capawesome-team/capacitor-file-picker#55]
Hi there,

sorry, I don't have an android device, so I have to ask. It is not apparent from the docs what happens if multiple is set to true and types to a filled array. Will it break? Will it throw an error? Will it be ignored and just a single select?

https://github.com/capawesome-team/capacitor-file-picker/blob/68df57224b6be1fe55a3550f9f6b48f2af96f3ae/src/definitions.ts#L13

Maybe it would be useful for me and others to extend the docs. (Or to add this functionality for Android :D )

**Comment by robingenz** [comment]
Hi,
`types` is simply ignored on Android if `multiple=true`.
Ref:
https://github.com/capawesome-team/capacitor-file-picker/blob/68df57224b6be1fe55a3550f9f6b48f2af96f3ae/android/src/main/java/io/capawesome/capacitorjs/plugins/filepicker/FilePickerPlugin.java#L42
