### ISSUE TITLE
bug: select multiple documents ios

### ISSUE THREAD

**Issue by CodeTriager** [capawesome-team/capacitor-file-picker#56]
**Plugin version:**

0.5.2

**Platform(s):**

ios

**Current behavior:**

When I want to select multiple documents on ios only the first document is selected and the dialog is closed.

**Expected behavior:**

The dialog should be open until all wanted documents are selected and import all of them.

**Steps to reproduce:**

I ran the example poject which is linked in the description. I activated the multiple open but no difference

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
I cannot reproduce the issue.

![file-picker-issue-56](https://user-images.githubusercontent.com/13857929/205146852-7c7e93d4-01f0-4687-b814-13fb00f72214.gif)

**Comment by robingenz** [comment]
Unfortunately, I need to be able to reproduce the problem on my device to help you. Feel free to debug the issue on your device and provide more information or create a PR with a fix.
