### ISSUE TITLE
feat: checkPermissions/requestPermissions

### ISSUE THREAD

**Issue by KANekT** [capawesome-team/capacitor-file-picker#57]
**Is your feature request related to a problem? Please describe:**
how I can checkPermissions/requestPermissions to files?

**Describe the solution you'd like:**

**Describe alternatives you've considered:**
use Filesystem plugin ? but it seems to me that everything should be in one plugin. It is a pity that such functionality was removed from the core of the capacitor

**Additional context:**

**Comment by robingenz** [comment]
Can you share your use case? In my tests on Android (Android 13, Pixel 5) and iOS, request permissions has not been necessary so far.
