### ISSUE TITLE
feat: Option for Max Limit when multiple: true

### ISSUE THREAD

**Issue by danbunkr** [capawesome-team/capacitor-file-picker#70]
**Is your feature request related to a problem? Please describe:**
It's a very common use case to apply a max limit for photo selection. When multiple: true it seems like the user in theory could select an infinite number of tiles and attempt to pass that data over the bridge which could degrade or crash the app. A simple maxLimit property that takes effect when multiple: true is a big win.

**Describe the solution you'd like:**
When multiple: true also have the option to limit the number of media options a user can select in a single file picking session.

**Describe alternatives you've considered:**
The user could always handle this on the front end but in my opinion its a worse experience to throw an error to the user when it could be avoided.

**Additional context:**
https://github.com/EinfachHans/cordova-plugin-advanced-imagepicker#present - This has some nice config items that might be worth investigating implementing in this plugin.

Thanks again for this!

**Comment by robingenz** [comment]
Thank you for the request. That is definitely missing.
There is already an issue for it: capawesome-team/capacitor-plugins#17. For this reason I am closing this issue as duplicate.
