### ISSUE TITLE
feat: modifiedDate per file in result of pickFiles()

### ISSUE THREAD

**Issue by MariaJulia** [capawesome-team/capacitor-file-picker#78]
I'm trying to save the last date of modification of uploaded files to get better information about the file's age and state. At the moment there is no possibility to get these information out of PickFilesResult.files when using the method FilePicker.pickFiles.

Would it be possible to add the date of last modification on the client's system per file in PickFilesResult?

**Comment by robingenz** [comment]
Yes, this is possible. I will add this tonight.

**Comment by robingenz** [comment]
This feature is now available in version `0.5.9`.
