### ISSUE TITLE
bug: pickImages() throws Cannot load representation of type public.image

### ISSUE THREAD

**Issue by Dresdn** [capawesome-team/capacitor-file-picker#82]
**Plugin version:**

0.5.9

**Platform(s):**

iOS

**Current behavior:**

Using `pickImages()`, once the images are selected and "Add" is clicked, the following error is thrown, and no `{ files }` are populated.

```
2023-01-25 13:43:02.712489-0700 App[50423:12554644] Error copying file type public.image. Error: Error Domain=NSItemProviderErrorDomain Code=-1000 "Cannot load representation of type public.image" UserInfo={NSLocalizedDescription=Cannot load representation of type public.image, NSUnderlyingError=0x600003f9d7a0 {Error Domain=NSCocoaErrorDomain Code=4101 "Couldn’t communicate with a helper application." UserInfo={NSUnderlyingError=0x600003f9dc50 {Error Domain=PHAssetExportRequestErrorDomain Code=0 "(null)" UserInfo={NSUnderlyingError=0x600003f9dd40 {Error Domain=PAMediaConversionServiceErrorDomain Code=2 "(null)" UserInfo=0x6000037471c0 (not displayed)}}}}}}
ERROR MESSAGE:  {"message":"Cannot load representation of type public.image","errorMessage":"Cannot load representation of type public.image"}
⚡️  [error] - {"message":"Cannot load representation of type public.image","errorMessage":"Cannot load representation of type public.image"}
```

**Expected behavior:**

I expect the selected images to returned to the `files` prop.

**Steps to reproduce:**

1. Create new React Ionic application
2. Wire up `pickImages()` to a button
3. Tap button, select images, tap "Add"

**Related code:**

```
  const [files, setFiles] = useState<PickedFile[]>([])

  const pickImages = async () => {
    const result = await FilePicker.pickImages({
      multiple: true,
    })
    setFiles(result.files)
  }
```

**Other information:**

I've tested this using iOS Simulator using iOS 14.5, 15.5, and 16.2.

However, this does work on a physical device with iOS 15.5.

I can upload the sample project I'm working with if that'd be helpful.

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

Installed Dependencies:

  @capacitor/cli: 4.6.2
  @capacitor/core: 4.6.2
  @capacitor/android: 4.6.2
  @capacitor/ios: 4.6.2

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Thank you for the detailed issue! 

So the issue does only occur in iOS simulator?

**Comment by Dresdn** [comment]
I randomly had a thought, and here's a fun series of steps to take:

1. Create a new iOS Simulator instance
2. Select some of the pre-provided images using `pickImages()`
3. Verify the error I posted originally is thrown
4. Download/Save a few images (via Add to Photos) to the Photo Library
5. Repeat Step 2 instead selecting images from Step 4
6. Verify `result.files` success
7. Repeat Step 2 using the pre-provided images
8. Verify `result.files` success

I'm not sure what's going on, but maybe this is a learning on how the iOS Simulator pre-populated images work? Super strange and not what I expected. Using the `@capacitor/camera` plugin to select an image has always worked, so I assumed the same behavior would happen.

I'll leave it up to you if you'd like to keep this open or close it, but the workaround seems to work.

**Comment by robingenz** [comment]
Thank you! I will have a look.

**Comment by Dresdn** [comment]
I'm going to close this. Turns out, it's a known issue in the simulator with the pink flower image: https://developer.apple.com/forums/thread/699155
