### ISSUE TITLE
check if a picked file needs to be downloaded from iCloud or not

### ISSUE THREAD

**Issue by mesqueeb** [capawesome-team/capacitor-file-picker#92]
test if there is a way for use to know wether or not a photo/video still needs to be downloaded from icloud when picked. And if so, can we get the download progress before the local copy process starts.

--

Main use case:

if the file doesn't need to be downloaded from iCloud
- in this case, _with the assumption it won't take long_, we can perhaps show a fullscreen blocking loading spinner, and automatically take the user to the next step after

if the file still needs to be downloaded from iCloud
- in this case, _with the assumption it might take pretty long_, we can have a non-blocking loading spinner somewhere in our app as a banner of the sorts, show some different loading text like: "downloading from iCloud & preparing file" and when it's finished show a button in this banner so the user can go to the next step.

--

This issue is related to #83, in the sense that fixing #83 might allow us do implement a better UX, nullifying the need for this issue in particular.

**Comment by mesqueeb** [comment]
edit: added main use case to original post

**Comment by robingenz** [comment]
@mesqueeb Unfortunately, I have not yet been able to find a suitable solution to determine whether a file needs to be downloaded first or not. There are different approaches, but they work differently for FilePicker and MediaPicker or under iOS14 and above iOS 13.

However, I was able to find another solution that supports your use case (see capawesome-team/capacitor-file-picker#93): A new `pickerDismissed` listener, which fires as soon as the picker modal closes. You can then check if the result of the FilePicker is already there and if not, you know that the files are being downloaded/processed and can show a hint to the user.

The advantage here is that this not only works for iCloud files but is a solution for a general delay.

Would that be an acceptable solution for you?

**Comment by mesqueeb** [comment]
@robingenz yes, I'll use capawesome-team/capacitor-file-picker#93 as a solution
